version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
        - db_data:/var/lib/postgresql/data

  web-api:
    build: ./andross-api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: your_db_port
      DB_NAME: your_database
      DB_USER: your_username
      DB_PASSWORD: your_password
      API_KEY: your_api_key
    ports:
      - "5000:5000"

  discord-bot:
    build: ./Andross/Andross
    restart: always
    depends_on:
      - db
      - web-api
    environment:
      API_URL: web-api
      API_KEY: your_api_key
      DISCORD_COMMAND_PREFIX: $
      DISCORD_TOKEN: your_discord_token

volumes:
  db_data: